apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpd-deployment
  labels:
    app: httpd
spec:
  replicas: 2
  selector:
    matchLabels:
      app: httpd
  template:
    metadata:
      labels:
        app: httpd
    spec:
      containers:
        - name: httpd
          image: httpd:latest
          ports:
            - containerPort: 80
      tolerations:
      - key: "only-use-for-tech-talk"
        operator: "Equal"
        value: "true"
        effect: "NoSchedule"
      nodeSelector:
        ownedby: "tech-talk"
